# Generated by Django 5.0 on 2024-03-08 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_factory_options'),
        ('manufacturers', '0007_manfcomponentrel_day_started_dhan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='p_type',
        ),
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
        migrations.AlterModelOptions(
            name='saler',
            options={'verbose_name': 'المورد', 'verbose_name_plural': 'الموردون'},
        ),
        migrations.RemoveField(
            model_name='products',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='products',
            name='got_it_from',
        ),
        migrations.RemoveField(
            model_name='products',
            name='name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='products',
            name='shop_in',
        ),
        migrations.AddField(
            model_name='products',
            name='mnaf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturers.manfcomponentrel', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.FloatField(default=0, verbose_name='السعر'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductTypes',
        ),
    ]
