# Generated by Django 5.0 on 2024-03-08 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_products_p_type_alter_products_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'منتج', 'verbose_name_plural': 'منتجات'},
        ),
    ]
