# Generated by Django 5.0 on 2024-03-08 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_products_shopin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='shopin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.shop', verbose_name='يعرض في محل'),
        ),
        migrations.DeleteModel(
            name='Factory',
        ),
    ]
