# Generated by Django 5.0 on 2024-03-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_products_shopin_delete_factory'),
        ('manufacturers', '0009_alter_factory_options_alter_manfcomponentrel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='saler',
            name='prod',
            field=models.ManyToManyField(to='manufacturers.components', verbose_name='القطع'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='how_many',
            field=models.FloatField(default=1, verbose_name='الكمية'),
        ),
    ]
