# Generated by Django 5.0 on 2024-03-02 14:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم القطعة')),
                ('how_many', models.IntegerField(default=0, verbose_name='عددها')),
            ],
            options={
                'verbose_name': 'القطعة',
                'verbose_name_plural': 'القطع',
            },
        ),
        migrations.CreateModel(
            name='ManF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المنتج')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'منتجات',
            },
        ),
        migrations.CreateModel(
            name='ManfComponentRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('howmany', models.FloatField(verbose_name='الكمية')),
                ('time_added', models.DateField(default=datetime.datetime.now)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturers.components', verbose_name='القطعة')),
                ('manf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturers.manf', verbose_name='القطعة')),
            ],
            options={
                'verbose_name': 'العلاقة بين المنتج والقطع ',
                'verbose_name_plural': 'العلافات بين المنتجات و القطع',
            },
        ),
    ]
