# Generated by Django 5.0 on 2024-03-02 15:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manfcomponentrel',
            name='howmany_days',
            field=models.IntegerField(default=0, verbose_name='ايام التصنيع'),
        ),
        migrations.RemoveField(
            model_name='manfcomponentrel',
            name='component',
        ),
        migrations.AlterField(
            model_name='manfcomponentrel',
            name='manf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturers.manf', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='manfcomponentrel',
            name='time_added',
            field=models.DateField(default=datetime.datetime.now, editable=False, verbose_name='وقت بدء التصنيع'),
        ),
        migrations.AddField(
            model_name='manfcomponentrel',
            name='component',
            field=models.ManyToManyField(blank=True, to='manufacturers.components', verbose_name='القطع'),
        ),
    ]
