# Generated by Django 5.0 on 2024-03-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0002_manfcomponentrel_howmany_days_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manfcomponentrel',
            options={'verbose_name': 'قطعة للتصنيع', 'verbose_name_plural': 'المصنع'},
        ),
        migrations.RenameField(
            model_name='manfcomponentrel',
            old_name='howmany_days',
            new_name='howmany_days_dhan',
        ),
        migrations.AddField(
            model_name='manfcomponentrel',
            name='have_perm_to_dhan',
            field=models.BooleanField(default=False, verbose_name='إذن الدهان'),
        ),
        migrations.AddField(
            model_name='manfcomponentrel',
            name='have_perm_to_manf',
            field=models.BooleanField(default=False, verbose_name='إذن التصنيع'),
        ),
        migrations.AddField(
            model_name='manfcomponentrel',
            name='have_perm_to_tshteb',
            field=models.BooleanField(default=False, verbose_name='إذن بالتشطيب'),
        ),
        migrations.AddField(
            model_name='manfcomponentrel',
            name='howmany_days_manf',
            field=models.IntegerField(default=0, verbose_name='ايام التصنيع'),
        ),
        migrations.AddField(
            model_name='manfcomponentrel',
            name='howmany_days_tshteb',
            field=models.IntegerField(default=0, verbose_name='ايام التصنيع'),
        ),
        migrations.AlterField(
            model_name='manfcomponentrel',
            name='howmany',
            field=models.IntegerField(default=1, verbose_name='الكمية'),
        ),
    ]
