# Generated by Django 5.0 on 2024-03-04 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0004_manfcomponentrelhowmanycomp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manfcomponentrel',
            name='howmany',
        ),
    ]
