# Generated by Django 5.0 on 2024-03-09 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0008_factory_manf_where'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factory',
            options={'verbose_name': 'مصنع', 'verbose_name_plural': 'اماكن التصنيع'},
        ),
        migrations.AlterModelOptions(
            name='manfcomponentrel',
            options={'permissions': [('can_give_perm', 'صلاحية تغير المرحلة')], 'verbose_name': 'قطعة للتصنيع', 'verbose_name_plural': 'اضف منتجات للتصنيع'},
        ),
    ]
