# Generated by Django 5.0 on 2024-02-28 21:53

import datetime
import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0003_absent'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pers_pho', models.ImageField(blank=True, upload_to='emp_photos', verbose_name='رفع صورة شخصية')),
                ('salary', models.FloatField(blank=True, null=True, verbose_name='دخله الشهري')),
                ('name', models.CharField(max_length=250, verbose_name='الإسم')),
                ('gender', models.CharField(choices=[('ذكر', 'ذكر'), ('انثى', 'انثى')], max_length=250, verbose_name='الجنس')),
                ('phone_nu', models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الهاتف')),
                ('id_for', models.CharField(blank=True, max_length=250, null=True, verbose_name='الرقم القومي')),
                ('date_ofj', models.DateField(default=datetime.datetime.now, verbose_name='وقت انضمامة للعمل')),
            ],
            options={
                'verbose_name': 'الحسابات الشخصية للموقع',
                'verbose_name_plural': 'الحسابات الشخصية للموقع',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
