# Generated by Django 5.0 on 2024-02-28 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0005_remove_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absent',
            name='fr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.customuser', verbose_name='الحساب'),
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'الحسابات الشخصية ', 'verbose_name_plural': 'الحسابات الشخصية للموقع'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('m', 'ذكر'), ('f', 'انثى')], default='m', max_length=250, verbose_name='الجنس'),
        ),
        migrations.DeleteModel(
            name='acc',
        ),
    ]
